# Generated by Django 2.1.5 on 2019-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_date', models.DateField(verbose_name='日付')),
                ('author', models.CharField(max_length=15, verbose_name='行った人')),
                ('sento_name', models.CharField(max_length=15, verbose_name='銭湯名')),
                ('sauna', models.BooleanField(verbose_name='サウナ有無')),
                ('outdoor_bath', models.BooleanField(verbose_name='露天風呂')),
                ('basic_charge', models.CharField(max_length=15, verbose_name='基本料金')),
                ('station', models.CharField(max_length=20, verbose_name='最寄り駅')),
                ('text', models.TextField(verbose_name='感想')),
            ],
        ),
    ]
