# Generated by Django 2.1.5 on 2019-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentodata',
            name='basic_charge',
            field=models.IntegerField(verbose_name='基本料金'),
        ),
    ]
